# Generated by Django 5.0.2 on 2024-02-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogcration_view',
        ),
    ]
