# Generated by Django 5.0.2 on 2024-02-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_blogcration_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcreation',
            name='picture',
        ),
    ]
