# Generated by Django 5.0.2 on 2024-03-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcreation_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcreation',
            name='blog_name',
        ),
    ]
